//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbilityForProfessional
    {
        public int abilityCodeForProfessional { get; set; }
        public string tzProfessional { get; set; }
        public int abilityCode { get; set; }
        public double taskLength { get; set; }
    
        public virtual TypeAbilityForProfession TypeAbilityForProfession { get; set; }
        public virtual Users Users { get; set; }
    }
}
