//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professional
    {
        public int code { get; set; }
        public string tz { get; set; }
        public string pic { get; set; }
        public string about { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
